/*
 * Copyright (c) 2026 Tom Henderson
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#ifndef NS3_DBM_PER_MHZ_H
#define NS3_DBM_PER_MHZ_H

#include "attribute-helper.h"
#include "attribute.h"
#include "double.h"
#include "units.h"

/**
 * @file
 * @ingroup attribute_DbmPerMhz
 * attribute value declaration for ns3::dBm_per_MHz_t (mp-units variant)
 *
 * wraps ns3::dBm_per_MHz_t
 */

namespace ns3
{

//  Additional docs for class DbmPerMhzValue:
/**
 * Hold variables of type ns3::dBm_per_MHz_t (power spectral density in dBm/MHz).
 *
 * The AttributeChecker accepts both DbmPerMhzValue and DoubleValue (treating
 * the bare double as dBm/MHz) for backward compatibility with legacy
 * attribute settings.
 */
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(ns3::dBm_per_MHz_t, DbmPerMhz);
ATTRIBUTE_ACCESSOR_DEFINE(DbmPerMhz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(ns3::dBm_per_MHz_t, DbmPerMhz, Double);

// Documentation for the MakeDbmPerMhzChecker with range bounds overload
// generated by ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER (the unbounded
// MakeDbmPerMhzChecker is documented by print-introspected-doxygen).
/**
 * @ingroup attribute_DbmPerMhz
 * @fn ns3::Ptr<const ns3::AttributeChecker> ns3::MakeDbmPerMhzChecker(ns3::dBm_per_MHz_t min,
 * ns3::dBm_per_MHz_t max) Make a DbmPerMhzChecker with a minimum and a maximum value.
 *
 * The minimum and maximum values are included in the allowed range.
 *
 * @param [in] min The minimum value.
 * @param [in] max The maximum value.
 * @returns The AttributeChecker.
 * @see AttributeChecker
 */

} // namespace ns3

#endif // NS3_DBM_PER_MHZ_H
