/*
 * Copyright (c) 2006 INRIA, 2010 NICTA
 *
 * SPDX-License-Identifier: GPL-2.0-only
 *
 * Author: Mathieu Lacage <mathieu.lacage@sophia.inria.fr>
 *         Quincy Tse <quincy.tse@nicta.com.au>
 */
#ifndef NS3_FATAL_ERROR_H
#define NS3_FATAL_ERROR_H

#include "fatal-impl.h"
#include "log.h" // NS_LOG_APPEND...

#include <cstdlib>
#include <exception>
#include <iostream>
#include <sstream>
#include <string_view>

// If stacktrace is available, print it on fatal errors
#ifdef STACKTRACE_LIBRARY_IS_LINKED
#include <stacktrace>
/**
 * @brief Macro prints the current stack trace to standard error.
 *
 * This macro is defined only if the stacktrace library is linked.
 */

#define NS_GET_STACKTRACE std::stacktrace::current()
#else
/**
 * @brief Macro does nothing if stacktrace library is not available.
 */
#define NS_GET_STACKTRACE ""
#endif

/**
 * @file
 * @ingroup fatal
 * @brief \c NS_FATAL_x macro definitions.
 */

/**
 * @ingroup core
 * @defgroup fatal Fatal Error Handlers
 *
 * @brief Functions to help clean up when a fatal error
 * is encountered.
 *
 * The functions in this group are used to perform
 * limited clean up, like flushing active streams, when
 * fatal errors are encountered (through assertion fail,
 * calls to NS_ABORT_* or calls to NS_FATAL_ERROR).
 *
 * Currently, other than flushing active ostreams, these
 * functions does not interfere with outside memory.  There
 * is still a residual risk that invalid ostream
 * pointers may be present, and may corrupt the memory
 * on the attempt to execute the flush() function.
 */

namespace ns3
{

/**
 * @ingroup fatal
 *
 * @brief Output string marking imminent invocation of std::terminate.
 *
 * This is useful to know when capturing output and you want to strip
 * system and compiler-dependent messages generated by std::terminate.
 */
constexpr std::string_view NS_FATAL_MSG{"NS_FATAL, terminating"};

} // namespace ns3

/**
 * @ingroup fatal
 *
 * @brief Fatal error reporting with a message, implementation.
 *
 * When this macro is hit at runtime the error details will
 * printed to \c stderr, including the message, file name and line number.
 * Optionally, if \c fatal is true, the macro
 * will invoke \c std::terminate().  If \c fatal is false,
 * the invoking function should return an error code to its caller,
 * which is expected to call NS_FATAL_ERROR to cause termination.
 *
 * @param [in] pre Preamble of error message, typically used by asserts.
 * @param [in] msg The error message to print, if not empty.
 * @param [in] fatal Call \c std::terminate() if true.
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 */
#define NS_FATAL_ERROR_IMPL(pre, msg, fatal)                                                       \
    do                                                                                             \
    {                                                                                              \
        std::stringstream fatalErrorStream;                                                        \
        fatalErrorStream << pre << "msg=\"" << msg << "\", ";                                      \
        NS_LOG_APPEND_TIME_PREFIX_IMPL(fatalErrorStream);                                          \
        NS_LOG_APPEND_NODE_PREFIX_IMPL(fatalErrorStream);                                          \
        fatalErrorStream << "file=" << std::string(__FILE__) << ", line=" << __LINE__;             \
        fatalErrorStream << "\n" << NS_GET_STACKTRACE;                                             \
        ::ns3::FatalImpl::FlushStreams();                                                          \
        if constexpr (fatal)                                                                       \
        {                                                                                          \
            std::cerr << fatalErrorStream.str() << std::endl;                                      \
            std::cerr << ns3::NS_FATAL_MSG << std::endl;                                           \
            std::terminate();                                                                      \
        }                                                                                          \
        else                                                                                       \
        {                                                                                          \
            throw std::runtime_error(fatalErrorStream.str());                                      \
        }                                                                                          \
    } while (false)

/**
 * @ingroup fatal
 *
 * @brief Fatal error reporting with no message, implementation.
 *
 * When this macro is hit at runtime the error details will
 * printed to \c stderr, including the file name and line number.
 * Optionally, if \c fatal is true, the macro
 * will invoke \c std::terminate().  If \c fatal is false,
 * the invoking function should return an error code to its caller,
 * which is expected to call NS_FATAL_ERROR to cause termination.
 *
 * @param [in] fatal Call \c std::terminate() if true.
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 */
#define NS_FATAL_ERROR_IMPL_NO_MSG(fatal)                                                          \
    NS_FATAL_ERROR_IMPL(std::string(""), std::string(""), fatal)

/**
 * @ingroup fatal
 *
 * @brief Report a fatal error and terminate.
 *
 * When this macro is hit at runtime, details of filename
 * and line number are printed to \c stderr, and the program
 * is halted by calling \c std::terminate(). This will
 * trigger any clean up code registered by
 * \c std::set_terminate (NS3 default is a stream-flushing
 * code), but may be overridden.
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 */
#define NS_FATAL_ERROR_NO_MSG() NS_FATAL_ERROR_IMPL_NO_MSG(true)

/**
 * @ingroup fatal
 *
 * @brief Report a fatal error, deferring termination.
 *
 * When this macro is hit at runtime, details of filename
 * and line number are printed to \c stderr, however the program
 * is _not_ halted.  It is expected that the function using this
 * macro will return an error code, and its caller will
 * invoke NS_FATAL_ERROR(msg) triggering std::terminate().
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 */
#define NS_FATAL_ERROR_NO_MSG_CONT() NS_FATAL_ERROR_IMPL_NO_MSG(false)

/**
 * @ingroup fatal
 *
 * @brief Report a fatal error with a message and terminate.
 *
 * @param [in] msg message to output when this macro is hit.
 *
 * When this macro is hit at runtime, the user-specified
 * error message are printed to \c stderr, followed by a call
 * to the NS_FATAL_ERROR_NO_MSG() macro which prints the
 * details of filename and line number to \c stderr. The
 * program will be halted by calling \c std::terminate(),
 * triggering any clean up code registered by
 * \c std::set_terminate (NS3 default is a stream-flushing
 * code, but may be overridden).
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 */
#define NS_FATAL_ERROR(msg) NS_FATAL_ERROR_IMPL(std::string(""), msg, true)

/**
 * @ingroup fatal
 *
 * @brief Report a fatal error with a message, deferring termination.
 *
 * When this macro is hit at runtime, details of filename
 * and line number are printed to \c stderr, however the program
 * is _not_ halted.  It is expected that the function using this
 * macro will return an error code, and its caller will
 * invoke NS_FATAL_ERROR(msg) triggering \c std::terminate().
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 */
#define NS_FATAL_ERROR_CONT(msg) NS_FATAL_ERROR_IMPL(std::string(""), msg, false)

/**
 * @ingroup fatal
 *
 * @brief Report a fatal error with a message, deferring termination.
 *
 * When this macro is hit at runtime, details of filename
 * and line number are printed to \c stderr, however the program
 * is _not_ halted.  It is expected that the function using this
 * macro will return an error code, and its caller will
 * invoke NS_FATAL_ERROR(msg) triggering \c std::terminate().
 *
 * This macro is enabled unconditionally in all builds,
 * including debug and optimized builds.
 *
 * In addition to a message, it also receives a preamble message, used for asserts.
 */
#define NS_FATAL_ERROR_CONT_PRE(pre, msg) NS_FATAL_ERROR_IMPL(pre, msg, false)

#endif /* FATAL_ERROR_H */
