/*
 * Copyright (c) 2026 Tom Henderson
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

#ifndef NS3_MHZ_H
#define NS3_MHZ_H

#include "attribute-helper.h"
#include "attribute.h"
#include "double.h"
#include "uinteger.h"
#include "units.h"

/**
 * @file
 * @ingroup attribute_Mhz
 * attribute value declaration for ns3::MHz_t (mp-units variant)
 *
 * wraps ns3::MHz_t
 */

namespace ns3
{

/**
 * @ingroup attributes
 * @defgroup attribute_Mhz Mhz Attribute
 * AttributeValue implementation for Mhz.
 * Hold variables of type ns3::MHz_t.
 */

//  Additional docs for class MhzValue:
/**
 * Hold variables of type ns3::MHz_t (mp-units frequency in megahertz).
 *
 * The associated MhzChecker accepts MhzValue, DoubleValue, and UintegerValue
 * (treating bare numeric values as MHz) for backward compatibility with
 * legacy attribute settings.
 */
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(ns3::MHz_t, Mhz);
ATTRIBUTE_ACCESSOR_DEFINE(Mhz);

// Documentation for the macro-generated members of MhzValue and the
// MakeMhzAccessor functions.  These are not documented by
// print-introspected-doxygen because the MhzChecker class is custom (it
// supports multiple converters: DoubleValue and UintegerValue) rather than
// generated by ATTRIBUTE_CHECKER_DEFINE.
/**
 * @ingroup attribute_Mhz
 * @fn ns3::MhzValue::MhzValue(const ns3::MHz_t& value)
 * Constructor.
 * @param[in] value The MHz value to use.
 */
/**
 * @ingroup attribute_Mhz
 * @fn ns3::MHz_t ns3::MhzValue::Get() const
 * @returns The MHz value.
 */
/**
 * @ingroup attribute_Mhz
 * @fn bool ns3::MhzValue::GetAccessor(T& value) const
 * Access the MHz value as type T.
 * @tparam T The type to cast to.
 * @param[out] value The MHz value, as type T.
 * @returns true.
 */
/**
 * @ingroup attribute_Mhz
 * @fn void ns3::MhzValue::Set(const ns3::MHz_t& value)
 * Set the value.
 * @param[in] value The value to adopt.
 */
/**
 * @ingroup attribute_Mhz
 * @var ns3::MHz_t ns3::MhzValue::m_value
 * The stored MHz instance.
 */
/**
 * @ingroup attribute_Mhz
 * @fn ns3::Ptr<const ns3::AttributeAccessor> ns3::MakeMhzAccessor(T1 a1)
 * @copydoc ns3::MakeAccessorHelper(T1)
 * @see AttributeAccessor
 * @hidecaller
 */
/**
 * @ingroup attribute_Mhz
 * @fn ns3::Ptr<const ns3::AttributeAccessor> ns3::MakeMhzAccessor(T1 a1, T2 a2)
 * @copydoc ns3::MakeAccessorHelper(T1,T2)
 * @see AttributeAccessor
 * @hidecaller
 */

/**
 * @ingroup attribute_Mhz
 * AttributeChecker for MhzValue.
 *
 * Accepts both MhzValue and DoubleValue (treating the bare double as MHz,
 * for backward compatibility with legacy attribute settings).
 */
class MhzChecker : public AttributeChecker
{
    Ptr<AttributeValue> CreateValidValue(const AttributeValue& value) const override
    {
        // Accept DoubleValue: treat numeric value as MHz (backward compatibility)
        const auto dblPtr = dynamic_cast<const DoubleValue*>(&value);
        if (dblPtr)
        {
            return AttributeChecker::CreateValidValue(MhzValue(dblPtr->Get() * MHz));
        }
        // Accept UintegerValue: treat integer value as MHz (backward compatibility)
        const auto uintPtr = dynamic_cast<const UintegerValue*>(&value);
        if (uintPtr)
        {
            return AttributeChecker::CreateValidValue(
                MhzValue(static_cast<double>(uintPtr->Get()) * MHz));
        }
        return AttributeChecker::CreateValidValue(value);
    }
};

/**
 * @ingroup attribute_Mhz
 * Make an unbounded MhzChecker.
 *
 * @returns The AttributeChecker.
 * @see AttributeChecker
 */
Ptr<const AttributeChecker> MakeMhzChecker();

/**
 * @ingroup attribute_Mhz
 * Make an MhzChecker with a minimum and a maximum value.
 *
 * The minimum and maximum values are included in the allowed range.
 *
 * @param [in] min The minimum value.
 * @param [in] max The maximum value.
 * @returns The AttributeChecker.
 * @see AttributeChecker
 */
Ptr<const AttributeChecker> MakeMhzChecker(ns3::MHz_t min, ns3::MHz_t max);

} // namespace ns3

#endif // NS3_MHZ_H
