#include "si-units-attributes.h"

using namespace ns3;

namespace si_units
{
/// @cond Doxygen warning against macro internal

// Angle
ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(degree_t, degree);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(degree_t, degree);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(radian_t, radian);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(radian_t, radian);


// Frequency
ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(Hz_t, Hz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(Hz_t, Hz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(kHz_t, kHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(kHz_t, kHz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(MHz_t, MHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(MHz_t, MHz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(GHz_t, GHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(GHz_t, GHz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(THz_t, THz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(THz_t, THz);


// Power
ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(dB_t, dB);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(dB_t, dB);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(dBr_t, dBr);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(dBr_t, dBr);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(dBm_t, dBm);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(dBm_t, dBm);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(mWatt_t, mWatt);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(mWatt_t, mWatt);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(Watt_t, Watt);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(Watt_t, Watt);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(dBm_per_Hz_t, dBm_per_Hz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(dBm_per_Hz_t, dBm_per_Hz);

ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(dBm_per_MHz_t, dBm_per_MHz);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(dBm_per_MHz_t, dBm_per_MHz);


// Ratio
ATTRIBUTE_CHECKER_IMPLEMENT_WITH_CONVERTER(percent_t, percent);
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(percent_t, percent);


// Time
ATTRIBUTE_CHECKER_IMPLEMENT_WITH_NAME(nSEC, "nSEC_t");
ATTRIBUTE_VALUE_IMPLEMENT_WITH_NAME(nSEC_t, nSEC);

/// @endcond
} // namespace si_units
