#ifndef SI_UNITS_ATTRIBS_H
#define SI_UNITS_ATTRIBS_H

// Include si-units from third-party library
#include <si-units>

#include "ns3/attribute-helper.h"
#include "ns3/attribute.h"
#include "ns3/double.h"

using namespace ns3;

namespace si_units
{
/// @cond To suppress doxygen checker

// Angle
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(degree_t, degree);
ATTRIBUTE_ACCESSOR_DEFINE(degree);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(degree_t, degree, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(radian_t, radian);
ATTRIBUTE_ACCESSOR_DEFINE(radian);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(radian_t, radian, Double);


// Frequency
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(Hz_t, Hz);
ATTRIBUTE_ACCESSOR_DEFINE(Hz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(Hz_t, Hz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(kHz_t, kHz);
ATTRIBUTE_ACCESSOR_DEFINE(kHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(kHz_t, kHz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(MHz_t, MHz);
ATTRIBUTE_ACCESSOR_DEFINE(MHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(MHz_t, MHz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(GHz_t, GHz);
ATTRIBUTE_ACCESSOR_DEFINE(GHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(GHz_t, GHz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(THz_t, THz);
ATTRIBUTE_ACCESSOR_DEFINE(THz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(THz_t, THz, Double);


// Power
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(dB_t, dB);
ATTRIBUTE_ACCESSOR_DEFINE(dB);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(dB_t, dB, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(dBr_t, dBr);
ATTRIBUTE_ACCESSOR_DEFINE(dBr);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(dBr_t, dBr, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(dBm_t, dBm);
ATTRIBUTE_ACCESSOR_DEFINE(dBm);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(dBm_t, dBm, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(mWatt_t, mWatt);
ATTRIBUTE_ACCESSOR_DEFINE(mWatt);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(mWatt_t, mWatt, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(Watt_t, Watt);
ATTRIBUTE_ACCESSOR_DEFINE(Watt);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(Watt_t, Watt, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(dBm_per_Hz_t, dBm_per_Hz);
ATTRIBUTE_ACCESSOR_DEFINE(dBm_per_Hz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(dBm_per_Hz_t, dBm_per_Hz, Double);

ATTRIBUTE_VALUE_DEFINE_WITH_NAME(dBm_per_MHz_t,
                                 dBm_per_MHz);
ATTRIBUTE_ACCESSOR_DEFINE(dBm_per_MHz);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(dBm_per_MHz_t, dBm_per_MHz, Double);


// Ratio
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(percent_t, percent);
ATTRIBUTE_ACCESSOR_DEFINE(percent);
ATTRIBUTE_CHECKER_DEFINE_WITH_CONVERTER(percent_t, percent, Double);


// Time
ATTRIBUTE_VALUE_DEFINE_WITH_NAME(nSEC_t, nSEC);
ATTRIBUTE_ACCESSOR_DEFINE(nSEC);
ATTRIBUTE_CHECKER_DEFINE(nSEC);

/// @endcond
} // namespace si_units

#endif // SI_UNITS_ATTRIBS_H
