@startuml
skinparam ranksep 20
skinparam dpi 125
skinparam packageTitleAlignment left
skinparam scale 2

package "ns3::aodvv2" {
    class Metric<T> {
        - uint8_t m_metricType
        - uint8_t m_maxMetric
        - std::function<double(const MetricNode<T>&, const MetricNode<T>&)> m_linkCost
        - std::function<double(const std::vector<MetricNode<T>>&)> m_routeCost
        - std::function<bool(const std::vector<MetricNode<T>>&, const std::vector<MetricNode<T>>&)> m_loopFree
        --
        + Metric(uint8_t metricType, uint8_t maxMetric, std::function<double(const MetricNode<T>, const MetricNode<T>)> linkCost, std::function<double(const std::vector<MetricNode<T>>&)> routeCost)
        + void SetMetricType(uint8_t metricType)
        + uint8_t GetMetricType() const
        + uint8_t GetMaxMetric() const
        + double Cost(const MetricNode<T> node1, const MetricNode<T> node2) const
        + double Cost(const std::vector<MetricNode<T>>& route) const
        + bool LoopFree(const std::vector<MetricNode<T>>& r1, const std::vector<MetricNode<T>>& r2) const
    }

    class MetricNode<T> {
        T m_address
    }
    Metric ..> MetricNode : uses
}

@enduml