@startuml
skinparam ranksep 20
skinparam dpi 125
skinparam packageTitleAlignment left
skinparam scale 2

package "ns3::aodvv2" {
    class RerrSet<T> {
        +RerrSet()
        +Time GetTimeout(T addr)
        +bool HasRerr(T unreachableAddr, T pktSource)
        +void Add(T unreachableAddr, T pktSource, Time timeout)
        +void Clear()
        +void Print(Ptr<OutputStreamWrapper> stream, Time::Unit unit = Time::S) const
    }

    class Rerr {
        +Time m_timeout
        +T m_unreachableAddr
        +T m_pktSource
        +Rerr(Time t, T unreachableAddr, T pktSource)
    }

    RerrSet ..> Rerr : uses
}

@enduml