@startuml
skinparam ranksep 20
skinparam dpi 125
skinparam packageTitleAlignment left
skinparam scale 2

package "ns3::aodvv2" {
    class DuplicatePacketDetection<T> {
        - IdCacheAlias m_idCache
        --
        + DuplicatePacketDetection(Time lifetime)
        + bool IsDuplicate(Ptr<const Packet> p, const T& header)
        + void SetLifetime(Time lifetime)
        + Time GetLifetime() const
    }

    class IdCache

    DuplicatePacketDetection ..> IdCache : uses
}

@enduml